# -*- coding: utf-8 -*-
"""CIE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MzfdLzil7-ls44UuWhuTrKu9KZqix_V
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

load = load_iris()
x = load.data
y = load.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier(
      criterion='entropy',
      max_depth=42,
      random_state=42
)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print('Accuracy:',accuracy_score(y_test, y_pred))
print('Classification Report:\n',classification_report(y_test, y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test, y_pred))